#pragma once
namespace Hashes {
	static char* AFTERHOURS[] = {
	"BLIMP3", "FREECRAWLER", "MENACER", "MULE4", "OPPRESSOR2", "PATRIOT2",
	"PBUS2", "POUNDER2", "SCRAMJET", "SPEEDO4", "STAFFORD", "STRIKEFORCE", "SWINGER",
	"TERBYTE"
	};
	static char* SOUTHERNSAN[] = {
		"CARACARA", "CHEBUREK", "DOMINATOR3", "ELLIE", "ENTITY2", "FAGALOA", "FLASHGT",
		"GB200", "HOTRING", "ISSI3", "JESTER3", "MICHELLI", "SEASPARROW", "TAIPAN", "TEZERACT",
		"TYRANT"
	};
	static char* Doomsday1[] = {
		"AUTARCH", "AVENGER", "BARRAGE", "CHERNOBOG", "COMET4", "COMET5",
		"DELUXO", "GT500", "HERMES", "HUSTLER", "KAMACHO","KHANJALI",
		"NEON", "PARIAH", "RAIDEN", "REVOLTER", "RIATA", "RIOT2", "SAVESTRA",
		"SC1", "SENTINEL3", "STREITER", "STROMBERG", "THRUSTER", "VISERIS",
		"VOLATOL", "YOSEMITE", "Z190"
	};
	static char* SMUGLERSRUN1[] = {
		"HAVOK", "RAPIDGT3", "RETINUE", "VIGILANTE", "VISIONE", "CYCLONE", "ALPHAZ1",
		"BOMBUSHKA", "HOWARD", "HUNTER", "MICROLIGHT", "MOGUL", "MOLOTOK", "NOKOTA", "PYRO",
		"ROGUE", "SEABREEZE", "STARLING", "TULA"
	};
	static char* GUNRUNNING1[] = {
		"APC", "ARDENT", "CADDY3", "CHEETAH2", "DUNE3", "HALFTRACK", "HAULER2",
		"INSUGENT3", "NIGHTSHARK", "OPPRESSOR", "PHANTOM3", "TAMPA3", "TECHNICAL3",
		"TORENO", "TRAILERLARGE", "TRAILERS4", "TRAILERSMALL2", "VAGNER", "XA21"
	};
	static char* CUNNINGSTUNTS1[] = {
		"BF400", "BRIOSO", "CLIFFHANGER", "CONTENDER", "GARGOYLE", "LE7B", "LYNX",
		"OMNIS", "RALLYTRUCK", "SHEAVA", "TAMPA2", "TROPHYTRUCK", "TROPHYTRUCK2",
		"TROPOS", "TYRUS"
	};
	static char* IMPORTEXPORT1[] = {
		"BLAZER5", "BOXVILLE5", "COMET3", "DIABLOUS", "DIABLOUS2", "DUNE4", "DUNE5",
		"ELEGY", "FCR", "FCR2", "ITALIGTB", "ITALIGTB2", "NERO", "NERO2", "PENETRATOR",
		"PHANTOM2", "RUINER2", "SPECTER", "SPECTER2", "TECHNICAL2", "TEMPESTA", "VOLTIC2",
		"WASTELANDER"
	};
	static char* Boats1[] = {
		"DINGHY", "DINGHY2", "DINGHY3", "DINGHY4", "JETMAX",
		"MARQUIS", "PREDATOR", "SEASHARK", "SEASHARK2", "SEASHARK3",
		"SPEEDER", "SPEEDER2", "SQUALO", "SUBMERSIBLE", "SUBMERSIBLE2",
		"SUNTRAP", "TORO", "TORO2", "TROPIC", "TROPIC2",
		"TUG"
	};
	static char* Commercial1[] = {
		"BENSON", "BIFF", "HAULER", "MULE", "MULE2",
		"MULE3", "PACKER", "PHANTOM", "POUNDER", "STOCKADE",
		"STOCKADE3"
	};
	static char* Compacts1[] = {
		"BLISTA", "BRIOSO", "DILETTANTE", "DILETTANTE2", "ISSI2",
		"PANTO", "PRAIRIE", "RHAPSODY"
	};
	static char* Coupes1[] = {
		"COGCABRIO", "EXEMPLAR", "F620", "FELON", "FELON2",
		"JACKAL", "ORACLE", "ORACLE2", "SENTINEL", "SENTINEL2",
		"WINDSOR", "WINDSOR2", "ZION", "ZION2"
	};
	static char* Cycles1[] = {
		"BMX", "CRUISER", "FIXTER", "SCORCHER", "TRIBIKE",
		"TRIBIKE2", "TRIBIKE3"
	};
	static char* Emergency1[] = {
		"AMBULANCE", "FBI", "FBI2", "FIRETRUK", "LGUARD",
		"PBUS", "PRANGER", "POLICE", "POLICE2", "POLICE3",
		"POLICE4", "POLICEB", "POLICEOLD1", "POLICEOLD2", "POLICET",
		"SHERIFF", "SHERIFF2", "RIOT"
	};
	static char* Helicopters1[] = {
		"ANNIHILATOR", "BLIMP", "BLIMP2", "BUZZARD", "BUZZARD2",
		"CARGOBOB", "CARGOBOB2", "CARGOBOB3", "CARGOBOB4", "FROGGER",
		"FROGGER2", "MAVERICK", "POLMAV", "SAVAGE", "SKYLIFT",
		"SUPERVOLITO", "SUPERVOLITO2", "SWIFT", "SWIFT2", "VALKYRIE",
		"VALKYRIE2", "VOLATUS"
	};
	static char* Industrial1[] = {
		"BULLDOZER", "CUTTER", "DUMP", "FLATBED", "GUARDIAN",
		"HANDLER", "MIXER", "MIXER2", "RUBBLE", "TIPTRUCK",
		"TIPTRUCK2"
	};
	static char* Military1[] = {
		"BARRACKS", "BARRACKS2", "BARRACKS3", "CRUSADER", "RHINO"
	};
	static char* Motorcycles1[] = {
		"AKUMA", "AVARUS", "BAGGER", "BATI", "BATI2",
		"BF400", "CARBONRS", "CHIMERA", "CLIFFHANGER", "DAEMON",
		"DAEMON2", "DEFILER", "DOUBLE", "ENDURO", "ESSKEY",
		"FAGGIO", "FAGGIO2", "FAGGIO3", "GARGOYLE", "HAKUCHOU",
		"HAKUCHOU2", "HEXER", "INNOVATION", "LECTRO", "MANCHEZ",
		"NEMESIS", "NIGHTBLADE", "PCJ", "RATBIKE", "RUFFIAN",
		"SANCHEZ", "SANCHEZ2", "SANCTUS", "SHOTARO", "SOVEREIGN",
		"THRUST", "VADER", "VINDICATOR", "VORTEX", "WOLFSBANE",
		"ZOMBIEA", "ZOMBIEB", "DIABLOUS", "DIABLOUS2", "FCR",
		"FCR2", "OPPRESSOR"
	};
	static char* Muscle1[] = {
		"BLADE", "BUCCANEER", "BUCCANEER2", "CHINO", "CHINO2",
		"COQUETTE3", "DOMINATOR", "DOMINATOR2", "DUKES", "DUKES2",
		"GAUNTLET", "GAUNTLET2", "FACTION", "FACTION2", "FACTION3",
		"HOTKNIFE", "LURCHER", "MOONBEAM", "MOONBEAM2", "NIGHTSHADE",
		"PHOENIX", "PICADOR", "RATLOADER", "RATLOADER2", "RUINER", "RUINER2", "RUINER3",
		"SABREGT", "SABREGT2", "SLAMVAN", "SLAMVAN2", "SLAMVAN3",
		"STALION", "STALION2", "TAMPA", "VIGERO", "VIRGO",
		"VIRGO2", "VIRGO3", "VOODOO", "VOODOO2"
	};
	static char* OffRoad1[] = {
		"BFINJECTION", "BIFTA", "BLAZER", "BLAZER2", "BLAZER3",
		"BLAZER4", "BODHI2", "BRAWLER", "DLOADER", "DUBSTA3",
		"DUNE", "DUNE2", "INSURGENT", "INSURGENT2", "KALAHARI",
		"MARSHALL", "MESA3", "MONSTER", "RANCHERXL", "RANCHERXL2",
		"REBEL", "REBEL2", "SANDKING", "SANDKING2", "TECHNICAL",
		"TROPHYTRUCK", "TROPHYTRUCK2", "TECHNICAL2", "DUNE4", "DUNE5",
		"BLAZER5"
	};
	static char* Planes1[] = {
		"BESRA", "CARGOPLANE", "CUBAN800", "DODO", "DUSTER",
		"HYDRA", "JET", "LAZER", "LUXOR", "LUXOR2",
		"MAMMATUS", "MILJET", "NIMBUS", "SHAMAL", "STUNT",
		"TITAN", "VELUM", "VELUM2", "VESTRA"
	};
	static char* Sedans1[] = {
		"ASEA", "ASEA2", "ASTEROPE", "COG55", "COG552",
		"COGNOSCENTI", "COGNOSCENTI2", "EMPEROR", "EMPEROR2", "EMPEROR3",
		"FUGITIVE", "GLENDALE", "INGOT", "INTRUDER", "LIMO2",
		"PREMIER", "PRIMO", "PRIMO2", "REGINA", "ROMERO",
		"SCHAFTER2", "SCHAFTER5", "SCHAFTER6", "STANIER", "STRATUM",
		"STRETCH", "SUPERD", "SURGE", "TAILGATER", "WARRENER",
		"WASHINGTON"
	};
	static char* Service1[] = {
		"AIRBUS", "BRICKADE", "BUS", "COACH", "RALLYTRUCK",
		"RENTALBUS", "TAXI", "TOURBUS", "TRASH", "TRASH2",
		"WASTELANDER",
	};
	static char* Sports1[] = {
		"ALPHA", "BANSHEE", "BESTIAGTS", "BLISTA2", "BLISTA3",
		"BUFFALO", "BUFFALO2", "BUFFALO3", "CARBONIZZARE", "COMET2",
		"COQUETTE", "ELEGY", "ELEGY2", "FELTZER2", "FUROREGT", "FUSILADE",
		"FUTO", "JESTER", "JESTER2", "KHAMELION", "KURUMA",
		"KURUMA2", "LYNX", "MASSACRO", "MASSACRO2", "NINEF",
		"NINEF2", "OMNIS", "PENUMBRA", "RAPIDGT", "RAPIDGT2",
		"RAPTOR", "SCHAFTER3", "SCHAFTER4", "SCHWARTZER", "SEVEN70",
		"SULTAN", "SURANO", "SPECTER", "SPECTER2", "TAMPA2", "TROPOS", "VERLIERER2",
		"RUINER2", "PHANTOM2", "RUSTON"
	};
	static char* SportsClassics1[] = {
		"BTYPE", "BTYPE2", "BTYPE3", "CASCO", "COQUETTE2",
		"FELTZER3", "JB700", "MAMBA", "MANANA", "MONROE",
		"PEYOTE", "PIGALLE", "STINGER", "STINGERGT", "TORNADO",
		"TORNADO2", "TORNADO3", "TORNADO4", "TORNADO5", "TORNADO6",
		"ZTYPE", "INFERNUS2", "TURISMO2",
	};
	static char* Super1[] = {
		"ADDER", "BANSHEE2", "BULLET", "CHEETAH", "ENTITYXF",
		"FMJ", "SHEAVA", "INFERNUS", "NERO", "NERO2","OSIRIS", "LE7B",
		"ITALIGTB", "ITALIGTB2", "PFISTER811", "PROTOTIPO", "REAPER", "SULTANRS", "T20",
		"TEMPESTA", "TURISMOR", "TYRUS", "VACCA", "VOLTIC", "ZENTORNO", "VOLTIC2", "PENETRATOR", "GP1"
	};
	static char* SUVs1[] = {
		"BALLER", "BALLER2", "BALLER3", "BALLER4", "BALLER5",
		"BALLER6", "BJXL", "CAVALCADE", "CAVALCADE2", "CONTENDER",
		"DUBSTA", "DUBSTA2", "FQ2", "GRANGER", "GRESLEY",
		"HABANERO", "HUNTLEY", "LANDSTALKER", "MESA", "MESA2",
		"PATRIOT", "RADI", "ROCOTO", "SEMINOLE", "SERRANO",
		"XLS", "XLS2"
	};
	static char* Trailer1[] = {
		"ARMYTANKER", "ARMYTRAILER", "ARMYTRAILER2", "BALETRAILER", "BOATTRAILER",
		"DOCKTRAILER", "FREIGHTTRAILER", "GRAINTRAILER", "PROPTRAILER", "RAKETRAILER",
		"TANKER", "TANKER2", "TR2", "TR3", "TR4",
		"TRAILERLOGS", "TRAILERS", "TRAILERS2", "TRAILERS3", "TRAILERSMALL",
		"TRFLAT", "TVTRAILER"
	};
	static char* Trains1[] = {
		"CABLECAR", "FREIGHT", "FREIGHTCAR", "FREIGHTCONT1", "FREIGHTCONT2",
		"FREIGHTGRAIN", "METROTRAIN", "TANKERCAR"
	};
	static char* Utility1[] = {
		"AIRTUG", "CADDY", "CADDY2", "DOCKTUG", "FORKLIFT",
		"MOWER", "RIPLEY", "SADLER", "SADLER2", "SCRAP",
		"TOWTRUCK", "TOWTRUCK2", "TRACTOR", "TRACTOR2", "TRACTOR3",
		"UTILLITRUCK", "UTILLITRUCK2", "UTILLITRUCK3"
	};
	static char* Vans1[] = {
		"BISON", "BISON2", "BISON3", "BOBCATXL", "BOXVILLE",
		"BOXVILLE2", "BOXVILLE3", "BOXVILLE4", "BURRITO", "BURRITO2",
		"BURRITO3", "BURRITO4", "BURRITO5", "CAMPER", "GBURRITO",
		"GBURRITO2", "JOURNEY", "MINIVAN", "MINIVAN2", "PARADISE",
		"PONY", "PONY2", "RUMPO", "RUMPO2", "RUMPO3",
		"SPEEDO", "SPEEDO2", "SURFER", "SURFER2", "TACO",
		"YOUGA", "YOUGA2"
	};
	static char* ArenaWars[] = {
		"BRUISER", "BRUISER2", "BRUISER3", "BRUTUS", "BRUTUS2",
		"BRUTUS3", "CERBERUS", "CERBERUS2", "CERBERUS3", "CLIQUE",
		"DEATHBIKE", "DEATHBIKE2", "DEATHBIKE3", "DEVESTE", "DEVIANT",
		"DOMINATOR4", "DOMINATOR5", "DOMINATOR6", "IMPALER", "IMPALER2",
		"IMPALER3", "IMPALER4", "IMPERATOR", "IMPERATOR2", "IMPERATOR3",
		"ISSI4", "ISSI5", "ISSI6", "ITALIGTO", "MONSTER3",
		"MONSTER4", "MONSTER5", "RCBANDITO", "SCARAB", "SCARAB2", "SCARAB3", "SCHLAGEN",
		"SLAMVAN4", "SLAMVAN5", "SLAMVAN6", "TOROS", "TULIP",
		"VAMOS", "ZR380", "ZR3802", "ZR3803"
	};
	static char* pedModels[] = {
		"mp_m_freemode_01", "player_zero", "player_one", "player_two", "s_m_m_movalien_01", "u_m_y_zombie_01", "u_m_y_imporage", "s_m_y_fireman_01", "a_f_y_topless_01", "u_f_y_poppymich", "a_m_y_acult_01", "ig_lamardavis", "ig_jimmydisanto", "ig_tracydisanto", "ig_johnnyklebitz", "ig_wade", "a_f_y_juggalo_01"
	};
	static char* animalsModels[] = {
	"a_c_chop", "a_c_rhesus", "a_c_chimp", "a_c_mtlion", "u_m_y_pogo_01", "a_c_boar", "a_c_pig", "a_c_coyote", "a_c_husky", "a_c_retriever", "a_c_rottweiler", "a_c_shepherd", "A_C_KillerWhale", "A_C_HumpBack", "A_C_Dolphin", "A_C_SharkHammer", "A_C_Cat_01", "A_C_Cow", "a_c_seagull", "a_c_fish", "a_c_pigeon", "a_c_rat", "a_c_deer", "a_c_chickenhawk"
	};
	static char* objects[136] = {
		"prop_bskball_01", "PROP_MP_RAMP_03", "PROP_MP_RAMP_02", "PROP_MP_RAMP_01", "PROP_JETSKI_RAMP_01", "PROP_WATER_RAMP_03",
		"PROP_VEND_SNAK_01", "PROP_TRI_START_BANNER", "PROP_TRI_FINISH_BANNER", "PROP_TEMP_BLOCK_BLOCKER", "PROP_SLUICEGATEL",
		"PROP_SKIP_08A", "PROP_SAM_01", "PROP_RUB_CONT_01B", "PROP_ROADCONE01A", "PROP_MP_ARROW_BARRIER_01", "PROP_HOTEL_CLOCK_01",
		"PROP_LIFEBLURB_02", "PROP_COFFIN_02B", "PROP_MP_NUM_1", "PROP_MP_NUM_2", "PROP_MP_NUM_3", "PROP_MP_NUM_4", "PROP_MP_NUM_5",
		"PROP_MP_NUM_6", "PROP_MP_NUM_7", "PROP_MP_NUM_8", "PROP_MP_NUM_9", "prop_xmas_tree_int", "prop_bumper_car_01", "prop_beer_neon_01",
		"prop_space_rifle", "prop_dummy_01", "prop_rub_trolley01a", "prop_wheelchair_01_s", "PROP_CS_KATANA_01", "PROP_CS_DILDO_01",
		"prop_armchair_01", "prop_bin_04a", "prop_chair_01a", "prop_dog_cage_01", "prop_dummy_plane", "prop_golf_bag_01", "prop_arcade_01",
		"hei_prop_heist_emp", "prop_alien_egg_01", "prop_air_towbar_01", "hei_prop_heist_tug", "prop_air_luggtrolley", "PROP_CUP_SAUCER_01",
		"prop_wheelchair_01", "prop_ld_toilet_01", "prop_acc_guitar_01", "prop_bank_vaultdoor", "p_v_43_safe_s", "p_spinning_anus_s", "prop_can_canoe",
		"prop_air_woodsteps", "Prop_weed_01", "prop_a_trailer_door_01", "prop_apple_box_01", "prop_air_fueltrail1", "prop_barrel_02a", "prop_barrel_float_1",
		"prop_barrier_wat_03b", "prop_air_fueltrail2", "prop_air_propeller01", "prop_windmill_01", "prop_Ld_ferris_wheel", "p_tram_crash_s", "p_oil_slick_01",
		"p_ld_stinger_s", "p_ld_soc_ball_01", "prop_juicestand", "p_oil_pjack_01_s", "prop_barbell_01", "prop_barbell_100kg", "p_parachute1_s", "p_cablecar_s",
		"prop_beach_fire", "prop_lev_des_barge_02", "prop_lev_des_barge_01", "prop_a_base_bars_01", "prop_beach_bars_01", "prop_air_bigradar", "prop_weed_pallet",
		"prop_artifact_01", "prop_attache_case_01", "prop_large_gold", "prop_roller_car_01", "prop_water_corpse_01", "prop_water_corpse_02", "prop_dummy_01", "prop_atm_01",
		"hei_prop_carrier_docklight_01", "hei_prop_carrier_liferafts", "hei_prop_carrier_ord_03", "hei_prop_carrier_defense_02", "hei_prop_carrier_defense_01", "hei_prop_carrier_radar_1",
		"hei_prop_carrier_radar_2", "hei_prop_hei_bust_01", "hei_prop_wall_alarm_on", "hei_prop_wall_light_10a_cr", "prop_afsign_amun", "prop_afsign_vbike", "prop_aircon_l_01", "prop_aircon_l_02",
		"prop_aircon_l_03", "prop_aircon_l_04", "prop_airhockey_01", "prop_air_bagloader", "prop_air_blastfence_01", "prop_air_blastfence_02", "prop_air_cargo_01a", "prop_air_chock_01",
		"prop_air_chock_03", "prop_air_gasbogey_01", "prop_air_generator_03", "prop_air_stair_02", "prop_amb_40oz_02", "prop_amb_40oz_03", "prop_amb_beer_bottle", "prop_amb_donut",
		"prop_amb_handbag_01", "prop_amp_01", "prop_anim_cash_pile_02", "prop_asteroid_01", "prop_arm_wrestle_01", "prop_ballistic_shield", "prop_bank_shutter", "prop_barier_conc_02b",
		"prop_barier_conc_05a", "prop_barrel_01a", "prop_bar_stool_01", "prop_basejump_target_01"
	};

	static char* stats[] = { "SCRIPT_INCREASE_STAM", "SCRIPT_INCREASE_STRN", "SCRIPT_INCREASE_LUNG", "SCRIPT_INCREASE_DRIV", "SCRIPT_INCREASE_FLY", "SCRIPT_INCREASE_SHO", "SCRIPT_INCREASE_STL", };
	static char* snacks[] = { "NO_BOUGHT_YUM_SNACKS", "NO_BOUGHT_HEALTH_SNACKS", "NO_BOUGHT_EPIC_SNACKS", "CIGARETTES_BOUGHT",
	"NUMBER_OF_ORANGE_BOUGHT", "NUMBER_OF_BOURGE_BOUGHT" };
	static char* tattoos[] = { "tattoo_fm_unlocks_1", "tattoo_fm_unlocks_2", "tattoo_fm_unlocks_3", "tattoo_fm_unlocks_4",
	"tattoo_fm_unlocks_5", "tattoo_fm_unlocks_6", "tattoo_fm_unlocks_7", "tattoo_fm_unlocks_8", "tattoo_fm_unlocks_9", "tattoo_fm_unlocks_10",
	"tattoo_fm_unlocks_11", "tattoo_fm_unlocks_12" };
	static char* wpncolors[] = {
	"MOLOTOV _ENEMY_KILLS",
	"CMBTPISTOL_ENEMY_KILLS",
	"PISTOL50_ENEMY_KILLS",
	"APPISTOL_ENEMY_KILLS",
	"MICROSMG_ENEMY_KILLS",
	"SMG_ENEMY_KILLS",
	"ASLTSMG_ENEMY_KILLS",
	"ASLTRIFLE_ENEMY_KILLS",
	"CRBNRIFLE_ENEMY_KILLS",
	"ADVRIFLE_ENEMY_KILLS",
	"MG_ENEMY_KILLS",
	"CMBTMG_ENEMY_KILLS",
	"ASLTMG_ENEMY_KILLS",
	"PUMP_ENEMY_KILLS",
	"SAWNOFF_ENEMY_KILLS",
	"BULLPUP_ENEMY_KILLS",
	"ASLTSHTGN_ENEMY_KILLS",
	"SNIPERRFL_ENEMY_KILLS",
	"HVYSNIPER_ENEMY_KILLS",
	"GRNLAUNCH_ENEMY_KILLS",
	"RPG_ENEMY_KILLS",
	"MINIGUNS_ENEMY_KILLS",
	"GRENADE_ENEMY_KILLS",
	"SMKGRENADE_ENEMY_KILLS",
	"STKYBMB_ENEMY_KILLS",
	"MOLOTOV_ENEMY_KILLS" };
	static char* clothings[] = {
		"CLTHS_AVAILABLE_FEET_1",
		"CLTHS_AVAILABLE_HAIR",
		"CLTHS_AVAILABLE_HAIR_1",
		"CLTHS_AVAILABLE_HAIR_2",
		"CLTHS_AVAILABLE_HAIR_3",
		"CLTHS_AVAILABLE_HAIR_4",
		"CLTHS_AVAILABLE_HAIR_5",
		"CLTHS_AVAILABLE_HAIR_6",
		"CLTHS_AVAILABLE_HAIR_7",
		"CLTHS_AVAILABLE_JBIB",
		"CLTHS_AVAILABLE_JBIB_1",
		"CLTHS_AVAILABLE_JBIB_2",
		"CLTHS_AVAILABLE_JBIB_3",
		"CLTHS_AVAILABLE_JBIB_4",
		"CLTHS_AVAILABLE_JBIB_5",
		"CLTHS_AVAILABLE_JBIB_6",
		"CLTHS_AVAILABLE_JBIB_7",
		"CLTHS_AVAILABLE_LEGS",
		"CLTHS_AVAILABLE_LEGS_1",
		"CLTHS_AVAILABLE_LEGS_2",
		"CLTHS_AVAILABLE_LEGS_3",
		"CLTHS_AVAILABLE_LEGS_4",
		"CLTHS_AVAILABLE_LEGS_5",
		"CLTHS_AVAILABLE_LEGS_6",
		"CLTHS_AVAILABLE_LEGS_7",
		"CLTHS_AVAILABLE_FEET",
		"CLTHS_AVAILABLE_FEET_1",
		"CLTHS_AVAILABLE_FEET_2",
		"CLTHS_AVAILABLE_FEET_3",
		"CLTHS_AVAILABLE_FEET_4",
		"CLTHS_AVAILABLE_FEET_5",
		"CLTHS_AVAILABLE_FEET_6",
		"CLTHS_AVAILABLE_FEET_7",
		"CLTHS_AVAILABLE_BERD",
		"CLTHS_AVAILABLE_BERD_1",
		"CLTHS_AVAILABLE_BERD_2",
		"CLTHS_AVAILABLE_BERD_3",
		"CLTHS_AVAILABLE_BERD_4",
		"CLTHS_AVAILABLE_BERD_5",
		"CLTHS_AVAILABLE_BERD_6",
		"CLTHS_AVAILABLE_BERD_7",
		"CLTHS_AVAILABLE_PROPS",
		"CLTHS_AVAILABLE_PROPS_1",
		"CLTHS_AVAILABLE_PROPS_2",
		"CLTHS_AVAILABLE_PROPS_3",
		"CLTHS_AVAILABLE_PROPS_4",
		"CLTHS_AVAILABLE_PROPS_5",
		"CLTHS_AVAILABLE_PROPS_6",
		"CLTHS_AVAILABLE_PROPS_7",
		"CLTHS_AVAILABLE_PROPS_8",
		"CLTHS_AVAILABLE_PROPS_9",
		"CLTHS_AVAILABLE_PROPS_10",
		"CLTHS_AVAILABLE_OUTFIT",
		"CLTHS_ACQUIRED_HAIR",
		"CLTHS_ACQUIRED_HAIR_1",
		"CLTHS_ACQUIRED_HAIR_2",
		"CLTHS_ACQUIRED_HAIR_3",
		"CLTHS_ACQUIRED_HAIR_4",
		"CLTHS_ACQUIRED_HAIR_5",
		"CLTHS_ACQUIRED_HAIR_6",
		"CLTHS_ACQUIRED_HAIR_7",
		"CLTHS_ACQUIRED_JBIB",
		"CLTHS_ACQUIRED_JBIB_1",
		"CLTHS_ACQUIRED_JBIB_2",
		"CLTHS_ACQUIRED_JBIB_3",
		"CLTHS_ACQUIRED_JBIB_4",
		"CLTHS_ACQUIRED_JBIB_5",
		"CLTHS_ACQUIRED_JBIB_6",
		"CLTHS_ACQUIRED_JBIB_7",
		"CLTHS_ACQUIRED_LEGS",
		"CLTHS_ACQUIRED_LEGS_1",
		"CLTHS_ACQUIRED_LEGS_2",
		"CLTHS_ACQUIRED_LEGS_3",
		"CLTHS_ACQUIRED_LEGS_4",
		"CLTHS_ACQUIRED_LEGS_5",
		"CLTHS_ACQUIRED_LEGS_6",
		"CLTHS_ACQUIRED_LEGS_7",
		"CLTHS_ACQUIRED_FEET",
		"CLTHS_ACQUIRED_FEET_1",
		"CLTHS_ACQUIRED_FEET_2",
		"CLTHS_ACQUIRED_FEET_3",
		"CLTHS_ACQUIRED_FEET_4",
		"CLTHS_ACQUIRED_FEET_5",
		"CLTHS_ACQUIRED_FEET_6",
		"CLTHS_ACQUIRED_FEET_7",
		"CLTHS_ACQUIRED_BERD",
		"CLTHS_ACQUIRED_BERD_1",
		"CLTHS_ACQUIRED_BERD_2",
		"CLTHS_ACQUIRED_BERD_3",
		"CLTHS_ACQUIRED_BERD_4",
		"CLTHS_ACQUIRED_BERD_5",
		"CLTHS_ACQUIRED_BERD_6",
		"CLTHS_ACQUIRED_BERD_7",
		"CLTHS_ACQUIRED_PROPS",
		"CLTHS_ACQUIRED_PROPS_1",
		"CLTHS_ACQUIRED_PROPS_2",
		"CLTHS_ACQUIRED_PROPS_3",
		"CLTHS_ACQUIRED_PROPS_4",
		"CLTHS_ACQUIRED_PROPS_5",
		"CLTHS_ACQUIRED_PROPS_6",
		"CLTHS_ACQUIRED_PROPS_7",
		"CLTHS_ACQUIRED_PROPS_8",
		"CLTHS_ACQUIRED_PROPS_9",
		"CLTHS_ACQUIRED_PROPS_10",
		"CLTHS_ACQUIRED_OUTFIT",
		"CLTHS_AVAILABLE_TORSO",
		"CLTHS_AVAILABLE_SPECIAL",
		"CLTHS_AVAILABLE_SPECIAL_1",
		"CLTHS_AVAILABLE_SPECIAL_2",
		"CLTHS_AVAILABLE_SPECIAL_3",
		"CLTHS_AVAILABLE_SPECIAL_4",
		"CLTHS_AVAILABLE_SPECIAL_5",
		"CLTHS_AVAILABLE_SPECIAL_6",
		"CLTHS_AVAILABLE_SPECIAL_7",
		"CLTHS_AVAILABLE_SPECIAL2",
		"CLTHS_AVAILABLE_SPECIAL2_1",
		"CLTHS_AVAILABLE_DECL",
		"CLTHS_AVAILABLE_TEETH",
		"CLTHS_AVAILABLE_TEETH_1",
		"CLTHS_AVAILABLE_TEETH_2",
		"CLTHS_ACQUIRED_TORSO",
		"CLTHS_ACQUIRED_SPECIAL",
		"CLTHS_ACQUIRED_SPECIAL_1",
		"CLTHS_ACQUIRED_SPECIAL_2",
		"CLTHS_ACQUIRED_SPECIAL_3",
		"CLTHS_ACQUIRED_SPECIAL_4",
		"CLTHS_ACQUIRED_SPECIAL_5",
		"CLTHS_ACQUIRED_SPECIAL_6",
		"CLTHS_ACQUIRED_SPECIAL_7",
		"CLTHS_ACQUIRED_SPECIAL2",
		"CLTHS_ACQUIRED_SPECIAL2_1",
		"CLTHS_ACQUIRED_DECL",
		"CLTHS_ACQUIRED_TEETH",
		"CLTHS_ACQUIRED_TEETH_1",
		"CLTHS_ACQUIRED_TEETH_2",
		"DLC_APPAREL_ACQUIRED_0",
		"DLC_APPAREL_ACQUIRED_1",
		"DLC_APPAREL_ACQUIRED_2",
		"DLC_APPAREL_ACQUIRED_3",
		"DLC_APPAREL_ACQUIRED_4",
		"DLC_APPAREL_ACQUIRED_5",
		"DLC_APPAREL_ACQUIRED_6",
		"DLC_APPAREL_ACQUIRED_7",
		"DLC_APPAREL_ACQUIRED_8",
		"DLC_APPAREL_ACQUIRED_9",
		"DLC_APPAREL_ACQUIRED_10",
		"DLC_APPAREL_ACQUIRED_11",
		"DLC_APPAREL_ACQUIRED_12",
		"DLC_APPAREL_ACQUIRED_13",
		"DLC_APPAREL_ACQUIRED_14",
		"DLC_APPAREL_ACQUIRED_15",
		"DLC_APPAREL_ACQUIRED_16",
		"DLC_APPAREL_ACQUIRED_17",
		"DLC_APPAREL_ACQUIRED_18",
		"DLC_APPAREL_ACQUIRED_19",
		"DLC_APPAREL_ACQUIRED_21",
		"DLC_APPAREL_ACQUIRED_22",
		"DLC_APPAREL_ACQUIRED_23",
		"DLC_APPAREL_ACQUIRED_24",
		"DLC_APPAREL_ACQUIRED_24",
		"DLC_APPAREL_ACQUIRED_25",
		"DLC_APPAREL_ACQUIRED_26",
		"DLC_APPAREL_ACQUIRED_27",
		"DLC_APPAREL_ACQUIRED_28",
		"DLC_APPAREL_ACQUIRED_29",
		"DLC_APPAREL_ACQUIRED_30",
		"DLC_APPAREL_ACQUIRED_31",
		"DLC_APPAREL_ACQUIRED_32",
		"DLC_APPAREL_ACQUIRED_33",
		"DLC_APPAREL_ACQUIRED_34",
		"DLC_APPAREL_ACQUIRED_35",
		"DLC_APPAREL_ACQUIRED_36",
		"DLC_APPAREL_ACQUIRED_37",
		"DLC_APPAREL_ACQUIRED_38",
		"DLC_APPAREL_ACQUIRED_39",
		"DLC_APPAREL_ACQUIRED_40",
		"ADMIN_CLOTHES_GV_BS_1",
		"ADMIN_CLOTHES_GV_BS_2",
		"ADMIN_CLOTHES_GV_BS_3",
		"ADMIN_CLOTHES_GV_BS_4",
		"ADMIN_CLOTHES_GV_BS_5",
		"ADMIN_CLOTHES_GV_BS_6",
		"ADMIN_CLOTHES_GV_BS_7",
		"ADMIN_CLOTHES_GV_BS_8",
		"ADMIN_CLOTHES_GV_BS_9",
		"ADMIN_CLOTHES_GV_BS_10",
		"ADMIN_CLOTHES_GV_BS_11",
		"ADMIN_CLOTHES_GV_BS_12",
		"ADMIN_CLOTHES_GV_BS_13",
		"ADMIN_CLOTHES_GV_BS_1",
		"ADMIN_CLOTHES_GV_BS_10",
		"ADMIN_CLOTHES_GV_BS_11",
		"ADMIN_CLOTHES_GV_BS_12"
	};

	static std::vector<PaintColour> PAINTS_NORMAL{
		{ "Black", 0, 0 },
		{ "Carbon Black", 147, 0 },
		{ "Graphite Black", 1, 0 },
		{ "Anthracite Black", 11, 0 },
		{ "Black Steel", 2, 0 },
		{ "Dark Steel", 3, 2 },
		{ "Silver", 4, 4 },
		{ "Bluish Silver", 5, 5 },
		{ "Rolled Steel", 6, 0 },
		{ "Shadow Silver", 7, 0 },
		{ "Stone Silver", 8, 0 },
		{ "Midnight Silver", 9, 0 },
		{ "Cast Iron Silver", 10, 0 },
		{ "Red", 27, 0 },
		{ "Torino Red", 28, 0 },
		{ "Formula Red", 29, 0 },
		{ "Lava Red", 150, 0 },
		{ "Blaze Red", 30, 0 },
		{ "Grace Red", 31, 0 },
		{ "Garnet Red", 32, 0 },
		{ "Sunset Red", 33, 0 },
		{ "Cabernet Red", 34, 0 },
		{ "Wine Red", 143, 0 },
		{ "Candy Red", 35, 0 },
		{ "Hot Pink", 135, 0 },
		{ "Pfister Pink", 137, 0 },
		{ "Salmon Pink", 136, 0 },
		{ "Sunrise Orange", 36, 0 },
		{ "Orange", 38, 0 },
		{ "Bright Orange", 138, 0 },
		{ "Gold", 99, 99 },
		{ "Bronze", 90, 102 },
		{ "Yellow", 88, 0 },
		{ "Race Yellow", 89, 0 },
		{ "Dew Yellow", 91, 0 },
		{ "Dark Green", 49, 0 },
		{ "Racing Green", 50, 0 },
		{ "Sea Green", 51, 0 },
		{ "Olive Green", 52, 0 },
		{ "Bright Green", 53, 0 },
		{ "Gasoline Green", 54, 0 },
		{ "Lime Green", 92, 0 },
		{ "Midnight Blue", 141, 0 },
		{ "Galaxy Blue", 61, 0 },
		{ "Dark Blue", 62, 0 },
		{ "Saxon Blue", 63, 0 },
		{ "Blue", 64, 0 },
		{ "Mariner Blue", 65, 0 },
		{ "Harbor Blue", 66, 0 },
		{ "Diamond Blue", 67, 0 },
		{ "Surf Blue", 68, 0 },
		{ "Nautical Blue", 69, 0 },
		{ "Racing Blue", 73, 0 },
		{ "Ultra Blue", 70, 0 },
		{ "Light Blue", 74, 0 },
		{ "Chocolate Brown", 96, 0 },
		{ "Bison Brown", 101, 0 },
		{ "Creek Brown", 95, 0 },
		{ "Feltzer Brown", 94, 0 },
		{ "Maple Brown", 97, 0 },
		{ "Beechwood Brown", 103, 0 },
		{ "Sienna Brown", 104, 0 },
		{ "Saddle Brown", 98, 0 },
		{ "Moss Brown", 100, 0 },
		{ "Woodbeech Brown", 102, 0 },
		{ "Straw Brown", 99, 0 },
		{ "Sandy Brown", 105, 0 },
		{ "Bleached Brown", 106, 0 },
		{ "Schafter Purple", 71, 0 },
		{ "Spinnaker Purple", 72, 0 },
		{ "Midnight Purple", 142, 0 },
		{ "Bright Purple", 145, 0 },
		{ "Cream", 107, 0 },
		{ "Ice White", 111, 0 },
		{ "Frost White", 112, 0 }
	};
	static std::vector<PaintColour> PAINTS_METALLIC{
		{ "Black", 0, 10 },
		{ "Carbon Black", 147, 4 },
		{ "Graphite Black", 1, 5 },
		{ "Anthracite Black", 11, 2 },
		{ "Black Steel", 2, 5 },
		{ "Dark Steel", 3, 6 },
		{ "Silver", 4, 111 },
		{ "Bluish Silver", 5, 111 },
		{ "Rolled Steel", 6, 4 },
		{ "Shadow Silver", 7, 5 },
		{ "Stone Silver", 8, 5 },
		{ "Midnight Silver", 9, 7 },
		{ "Cast Iron Silver", 10, 7 },
		{ "Red", 27, 36 },
		{ "Torino Red", 28, 28 },
		{ "Formula Red", 29, 28 },
		{ "Lava Red", 150, 42 },
		{ "Blaze Red", 30, 36 },
		{ "Grace Red", 31, 27 },
		{ "Garnet Red", 32, 25 },
		{ "Sunset Red", 33, 47 },
		{ "Cabernet Red", 34, 47 },
		{ "Wine Red", 143, 31 },
		{ "Candy Red", 35, 25 },
		{ "Hot Pink", 135, 135 },
		{ "Pfister Pink", 137, 3 },
		{ "Salmon Pink", 136, 5 },
		{ "Sunrise Orange", 36, 26 },
		{ "Orange", 38, 37 },
		{ "Bright Orange", 138, 89 },
		{ "Gold", 37, 106 },
		{ "Bronze", 90, 102 },
		{ "Yellow", 88, 88 },
		{ "Race Yellow", 89, 88 },
		{ "Dew Yellow", 91, 91 },
		{ "Dark Green", 49, 52 },
		{ "Racing Green", 50, 53 },
		{ "Sea Green", 51, 66 },
		{ "Olive Green", 52, 59 },
		{ "Bright Green", 53, 59 },
		{ "Gasoline Green", 54, 60 },
		{ "Lime Green", 92, 92 },
		{ "Midnight Blue", 141, 73 },
		{ "Galaxy Blue", 61, 63 },
		{ "Dark Blue", 62, 68 },
		{ "Saxon Blue", 63, 87 },
		{ "Blue", 64, 68 },
		{ "Mariner Blue", 65, 87 },
		{ "Harbor Blue", 66, 60 },
		{ "Diamond Blue", 67, 67 },
		{ "Surf Blue", 68, 68 },
		{ "Nautical Blue", 69, 74 },
		{ "Racing Blue", 73, 73 },
		{ "Ultra Blue", 70, 70 },
		{ "Light Blue", 74, 74 },
		{ "Chocolate Brown", 96, 95 },
		{ "Bison Brown", 101, 95 },
		{ "Creek Brown", 95, 97 },
		{ "Feltzer Brown", 94, 104 },
		{ "Maple Brown", 97, 98 },
		{ "Beechwood Brown", 103, 104 },
		{ "Sienna Brown", 104, 104 },
		{ "Saddle Brown", 98, 95 },
		{ "Moss Brown", 100, 100 },
		{ "Woodbeech Brown", 102, 105 },
		{ "Straw Brown", 99, 106 },
		{ "Sandy Brown", 105, 105 },
		{ "Bleached Brown", 106, 106 },
		{ "Schafter Purple", 71, 145 },
		{ "Spinnaker Purple", 72, 64 },
		{ "Midnight Purple", 146, 145 },
		{ "Bright Purple", 145, 74 },
		{ "Cream", 107, 107 },
		{ "Ice White", 111, 0 },
		{ "Frost White", 112, 0 }
	};
	static std::vector<PaintColour> PAINTS_MATTE{
		{ "Black", 12, 0 },
		{ "Gray", 13, 0 },
		{ "Light Gray", 14, 0 },
		{ "Ice White", 131, 0 },
		{ "Blue", 83, 0 },
		{ "Dark Blue", 82, 0 },
		{ "Midnight Blue", 84, 0 },
		{ "Midnight Purple", 149, 0 },
		{ "Schafter Purple", 148, 0 },
		{ "Red", 39, 0 },
		{ "Dark Red", 40, 0 },
		{ "Orange", 41, 0 },
		{ "Yellow", 42, 0 },
		{ "Lime Green", 55, 0 },
		{ "Green", 128, 0 },
		{ "Forest Green", 151, 0 },
		{ "Foliage Green", 155, 0 },
		{ "Olive Drab", 152, 0 },
		{ "Dark Earth", 153, 0 },
		{ "Desert Tan", 154, 0 }
	};
	static std::vector<PaintColour> PAINTS_METAL{
		{ "Brushed Steel", 117, 18 },
		{ "Brushed Black Steel", 118, 3 },
		{ "Brushed Aluminum", 119, 5 },
		{ "Pure Gold", 158, 160 },
		{ "Brushed Gold", 159, 160 }
	};
	static std::vector<PaintColour> PAINTS_PEARL{
		{ "Black", -1, 0 },
		{ "Carbon Black", -1, 147 },
		{ "Graphite Black", -1, 1 },
		{ "Anthracite Black", -1, 11 },
		{ "Black Steel", -1, 2 },
		{ "Dark Steel", -1, 3 },
		{ "Silver", -1, 4 },
		{ "Bluish Silver", -1, 5 },
		{ "Rolled Steel", -1, 6 },
		{ "Shadow Silver", -1, 7 },
		{ "Stone Silver", -1, 8 },
		{ "Midnight Silver", -1, 9 },
		{ "Cast Iron Silver", -1, 10 },
		{ "Red", -1, 27 },
		{ "Torino Red", -1, 28 },
		{ "Formula Red", -1, 29 },
		{ "Lava Red", -1, 150 },
		{ "Blaze Red", -1, 30 },
		{ "Grace Red", -1, 31 },
		{ "Garnet Red", -1, 32 },
		{ "Sunset Red", -1, 33 },
		{ "Cabernet Red", -1, 34 },
		{ "Wine Red", -1, 143 },
		{ "Candy Red", -1, 35 },
		{ "Hot Pink", -1, 135 },
		{ "Pfister Pink", -1, 137 },
		{ "Salmon Pink", -1, 136 },
		{ "Sunrise Orange", -1, 36 },
		{ "Orange", -1, 38 },
		{ "Bright Orange", -1, 138 },
		{ "Gold", -1, 37 },
		{ "Bronze", -1, 90 },
		{ "Yellow", -1, 88 },
		{ "Race Yellow", -1, 89 },
		{ "Dew Yellow", -1, 91 },
		{ "Dark Green", -1, 49 },
		{ "Racing Green", -1, 50 },
		{ "Sea Green", -1, 51 },
		{ "Olive Green", -1, 52 },
		{ "Bright Green", -1, 53 },
		{ "Gasoline Green", -1, 54 },
		{ "Lime Green", -1, 92 },
		{ "Midnight Blue", -1, 141 },
		{ "Galaxy Blue", -1, 61 },
		{ "Dark Blue", -1, 62 },
		{ "Saxon Blue", -1, 63 },
		{ "Blue", -1, 64 },
		{ "Mariner Blue", -1, 65 },
		{ "Harbor Blue", -1, 66 },
		{ "Diamond Blue", -1, 67 },
		{ "Surf Blue", -1, 68 },
		{ "Nautical Blue", -1, 69 },
		{ "Racing Blue", -1, 73 },
		{ "Ultra Blue", -1, 70 },
		{ "Light Blue", -1, 74 },
		{ "Chocolate Brown", -1, 96 },
		{ "Bison Brown", -1, 101 },
		{ "Creek Brown", -1, 95 },
		{ "Feltzer Brown", -1, 94 },
		{ "Maple Brown", -1, 97 },
		{ "Beechwood Brown", -1, 103 },
		{ "Sienna Brown", -1, 104 },
		{ "Saddle Brown", -1, 98 },
		{ "Moss Brown", -1, 100 },
		{ "Woodbeech Brown", -1, 102 },
		{ "Straw Brown", -1, 99 },
		{ "Sandy Brown", -1, 105 },
		{ "Bleached Brown", -1, 106 },
		{ "Schafter Purple", -1, 71 },
		{ "Spinnaker Purple", -1, 72 },
		{ "Midnight Purple", -1, 146 },
		{ "Bright Purple", -1, 145 },
		{ "Cream", -1, 107 },
		{ "Ice White", -1, 111 },
		{ "Frost White", -1, 112 },
		{ "Secret Gold", -1, 160 }
	};
	static std::vector<PaintColour> PAINTS_WHEELS
	{
		{ "Default", 156, -1 },
		{ "Black", 0, -1 },
		{ "Carbon Black", 1, -1 },
		{ "Anthracite Black", 11, -1 },
		{ "Black Steel", 2, -1 },
		{ "Stone Silver", 8, -1 },
		{ "Frost White", 122, -1 },
		{ "Red", 27, -1 },
		{ "Blaze Red", 30, -1 },
		{ "Garnet Red", 45, -1 },
		{ "Candy Red", 35, -1 },
		{ "Sunset Red", 33, -1 },
		{ "Salmon Pink", 136, -1 },
		{ "Hot Pink", 135, -1 },
		{ "Sunrise Orange", 36, -1 },
		{ "Orange", 41, -1 },
		{ "Bright Orange", 138, -1 },
		{ "Gold", 37, -1 },
		{ "Straw Brown", 99, -1 },
		{ "Dark Copper", 90, -1 },
		{ "Dark Ivory", 95, -1 },
		{ "Dark Brown", 115, -1 },
		{ "Bronze", 109, -1 },
		{ "Dark Earth", 153, -1 },
		{ "Desert Tan", 154, -1 },
		{ "Yellow", 88, -1 },
		{ "Race Yellow", 89, -1 },
		{ "Yellow Bird", 91, -1 },
		{ "Lime Green", 55, -1 },
		{ "Pea Green", 125, -1 },
		{ "Green", 53, -1 },
		{ "Dark Green", 56, -1 },
		{ "Olive Green", 151, -1 },
		{ "Midnight Blue", 82, -1 },
		{ "Royal Blue", 64, -1 },
		{ "Baby Blue", 87, -1 },
		{ "Bright Blue", 70, -1 },
		{ "Flourescent Blue", 140, -1 },
		{ "Slate Blue", 81, -1 },
		{ "Schafter Purple", 145, -1 },
		{ "Midnight Purple", 142, -1 }
	};

	static std::vector<NameChanger> COLOR_CODES
	{
		{ "Plain White", "" },
		{ "~r~Red", "~r~" },
		{ "~g~Green", "~g~" },
		{ "~b~Blue", "~b~" },
		{ "~italic~Italic Font", "~italic~" },
		{ "~bold~Bold Font", "~bold~" }
		/*{ "~y~Yellow", "~y~" },
		{ "~p~Purple", "~p~" },
		{ "~o~Orange", "~o~" },
		{ "~c~Grey", "~c~" },
		{ "~m~Dark Grey", "~m~" },
		{ "~u~Black", "~u~" },
		{ "~s~White", "~s~" },
		{ "~d~Dark Blue", "~d~" },
		{ "~f~Light Blue", "~f~" },*/
	};
}